### ISSUE TITLE
Does not recompute in a Glimmer component

### ISSUE THREAD

**Issue by lolmaus** [pzuraq/macro-decorators#5]
Got this decorator:

```ts
function scaledProperty(propertyName) {
  return macro({
    get (target) {
      return target[propertyName] * target.args.scale / 1000;
    },
  });
}
```

It does not recompute when `@scale` passed into the component changes.

Same for the dynamic property — when its value changes, the macro does not recompute.

Is this my mistake?

**Comment by pzuraq** [comment]
Hey @lolmaus, thanks for reporting this. I've attempted to make a reproduction on Glitch: https://glitch.com/~pitch-lilac

It appears to be working, using the latest version of Ember and Glimmer components. Can you provide some more information about your setup? Are you using an older version of Ember/Glimmer components?

**Comment by lolmaus** [comment]
Thx for looking into this!

I probably do not fully understand all the implications of tracked priperties interop with classic approaches.
